# Generated by Django 5.2.6 on 2025-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_username', models.CharField(max_length=20)),
                ('user_describtion', models.CharField(max_length=200)),
                ('user_profile_picture', models.CharField(max_length=100)),
                ('user_banner', models.CharField(max_length=100)),
            ],
        ),
    ]
