# Generated by Django 5.2.6 on 2025-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='ended_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='evented_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='started_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
