# Generated by Django 5.2.6 on 2025-11-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_end_date_event_ended_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ended_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='evented_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='started_date',
            new_name='start_date',
        ),
    ]
