# Generated by Django 5.2.6 on 2025-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_ended_date_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='started_date',
            field=models.DateField(null=True),
        ),
    ]
