# Generated by Django 5.2.6 on 2025-11-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_started_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='started_date',
        ),
    ]
