# Generated by Django 5.2.6 on 2025-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_event_started_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
