# Generated by Django 5.2.6 on 2025-10-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=200)),
                ('event_archieved', models.BooleanField()),
                ('event_starttime', models.DateTimeField()),
                ('event_endtime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
