# Generated by Django 5.2.6 on 2025-10-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_banner_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
