# Generated by Django 5.2.6 on 2025-10-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['id']},
        ),
    ]
