# Generated by Django 5.2.6 on 2025-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reject', 'reject'), ('approved', 'approved')], default='pending', max_length=30),
        ),
    ]
