# Generated by Django 5.2.6 on 2025-11-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0002_alter_friendrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='friend_id',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
