# Generated by Django 5.2.6 on 2025-10-26 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('reject', 'reject'), ('approved', 'approved')], default='pending', max_length=10)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_request_group_id', to='group.group')),
                ('invited_user_id', models.ForeignKey(db_column='invited_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_request_invited_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
