# Generated by Django 5.2.6 on 2025-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
