# Generated by Django 5.2.6 on 2025-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_request', '0002_alter_grouprequest_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprequest',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='grouprequest',
            old_name='invited_user_id',
            new_name='invited_user',
        ),
    ]
