# Generated by Django 5.2.6 on 2025-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('banner_image', models.CharField(max_length=100)),
                ('max_member', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group',
                'ordering': ['-created_at'],
            },
        ),
    ]
