# Generated by Django 5.2.6 on 2025-10-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('banner_image', models.CharField(max_length=100)),
                ('max_member', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group',
                'ordering': ['-created_at'],
            },
        ),
    ]
