# Generated by Django 5.2.6 on 2025-10-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_uuid', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=50)),
                ('group_image', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
