# Generated by Django 5.2.6 on 2025-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
