# Generated by Django 5.2.6 on 2025-11-07 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_rename_owner_id_group_owner'),
        ('group_member', '0002_rename_group_id_groupmember_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='Member_role_group_id', to='group.group')),
                ('group_member', models.ForeignKey(db_column='group_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='Member_role_group_member_id', to='group_member.groupmember')),
            ],
            options={
                'db_table': 'member_role',
                'ordering': ['created_at'],
            },
        ),
    ]
