# Generated by Django 5.2.6 on 2025-10-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['-created_at']},
        ),
    ]
