# Generated by Django 5.2.6 on 2025-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='member_id',
            new_name='member',
        ),
    ]
