# Generated by Django 5.2.6 on 2025-10-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('group_member', '0002_alter_groupmember_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_member_group_id', to='group.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_member_member_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
