# Generated by Django 5.2.6 on 2025-11-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('group_member', '0002_rename_group_id_groupmember_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], default='maybe', max_length=10)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='available_date_event_id', to='event.event')),
                ('group_member', models.ForeignKey(db_column='group_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='available_date_group_member', to='group_member.groupmember')),
            ],
            options={
                'db_table': 'available_date',
                'ordering': ['id'],
            },
        ),
    ]
