# Generated by Django 5.2.6 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
