name: Django CI (backend, SQLite)

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Safety net in case something's missing from requirements.txt
          pip install django djangorestframework python-dotenv django-cors-headers django-rest-knox || true

      - name: Create .env for CI
        run: |
          cat > .env << 'EOF'
          DEBUG=1
          SECRET_KEY=ci-secret-key-change-me
          ALLOWED_HOSTS=*
          EOF

      - name: Migrate (SQLite)
        env:
          USE_SQLITE_FOR_TESTS: "1"
          DJANGO_SETTINGS_MODULE: backend.settings
        run: |
          python manage.py migrate --noinput

      - name: Run ONLY friend_request tests
        env:
          USE_SQLITE_FOR_TESTS: "1"
          DEBUG: "1"
          SECRET_KEY: ci-secret-key-change-me
          DJANGO_SETTINGS_MODULE: backend.settings
        run: |
          # Optional: show what Django finds
          python -c "import sys, os; print('CWD:', os.getcwd()); print('PYTHONPATH:', sys.path[0])"
          # Optional: check for unapplied migrations (doesn't fail CI)
          python manage.py makemigrations --check --dry-run || true
          # Target the module explicitly to avoid 'backend.friend_request' import path confusion
          python manage.py test friend_request.tests -v 2
