name: PSU Linting

on:
  push:
    branches-ignore: [main]   # push to feature branches
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  lint-backend:
    name: Lint Backend (Python/Django)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Linters/formatters
          pip install ruff==0.6.9 black==24.8.0

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (check formatting)
        run: black --check .

      - name: Django sanity check (non-blocking)
        run: |
          python manage.py check
          python manage.py makemigrations --check --dry-run
        continue-on-error: true

  lint-frontend:
    name: Lint Frontend (Typecheck & Build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Build (non-blocking)
        run: npm run build
        continue-on-error: true
