# This is a GitHub Actions workflow file.
# It defines a set of jobs that will be run on GitHub's servers.

name: Python application test

on:
  # This section defines WHEN the workflow runs
  push:
    branches:
      - "main"
      - "test/cd-pipeline"  # <-- I added this so it runs on your branch
  pull_request:
    branches:
      - "main"
      - "test/cd-pipeline"  # <-- I added this for pull requests to your branch
  
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      # This step downloads your repository into the runner.

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10" 
        # You can change this to your desired Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # This step installs pytest and any dependencies from requirements.txt.
      # If your dependency file has a different name, please update it here.

    - name: Run tests
      run: |
        # This command will run the specific test file you mentioned.
        pytest friend_request/test.py
      # If your test setup is different (e.g., just 'pytest' to run all),
      # you can change this command.

