# This is a GitHub Actions workflow file.
# It defines a set of jobs that will be run on GitHub's servers.

name: Python application test

on:
  # This section defines WHEN the workflow runs
  push:
    branches:
      - "main"
      - "test/cd-pipeline"  # <-- I added this so it runs on your branch
  pull_request:
    branches:
      - "main"
      - "test/cd-pipeline"  # <-- I added this for pull requests to your branch
  
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      # This step downloads your repository into the runner.

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10" 
        # You can change this to your desired Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-django  # <-- Added pytest-django
        
        # Look for requirements.txt in root or backend/
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        elif [ -f backend/requirements.txt ]; then 
          pip install -r backend/requirements.txt
        else
          echo "ERROR: requirements.txt not found in root or backend/ directory"
          exit 1
        fi
      # This step installs pytest and any dependencies from requirements.txt.
      # It now checks both the root and the backend/ folder.

    # - name: Run tests
    #   env:
    #     # This tells settings.py to use the test_db.sqlite3
    #     USE_SQLITE_FOR_TESTS: "1" 
    #     # This tells pytest-django which settings file to load
    #     DJANGO_SETTINGS_MODULE: "backend.settings"
    #     # This tells Python to look for apps inside the 'backend' folder
    #     PYTHONPATH: ./backend
    #   run: |
    #     # Set up the test database schema
    #     python backend/manage.py migrate
        
    #     # Run the specific test file
    #     pytest backend/friend_request/test.py

